version: '3.1'
services:
  askalien-admin:
    image: askalien-admin:4.1.1
    ports:
      - "8080:8080"
    environment: 
      - APPLICATION_WEBSITE=http://localhost:4200
      - AUTHENTICATOR_SERVER=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_vXjuddh4O
      - DATABASE_URL=postgresql://postgres:postgres@10.0.0.32/mythidb
