# fly.toml file generated for askalien-admin on 2022-12-09T10:18:50-03:00

app = "askalien-admin"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "mmuniz/askalien-admin:4.1.2"

[env]
    APPLICATION_WEBSITE="*"
    AUTHENTICATOR_SERVER="https://cognito-idp.us-east-1.amazonaws.com/us-east-1_vXjuddh4O"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
