server.port: ${PORT:8080}
spring:
  profiles:
    active: prod
  r2dbc:
    url: r2dbc:${DATABASE_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  ${AUTHENTICATOR_SERVER}/.well-known/jwks.json


logging:
  level:
    org.springframework:
      data.r2dbc: DEBUG
